variable "region" {}
variable "profile" {}
variable "vpc_cidr_block" {}
variable "public_subnet_cidr" {}
variable "private_subnet_cidr" {}
variable "public_subnet_count" {}
variable "private_subnet_count" {}
variable "environment" {}
variable "availability_zones" {}
variable "keypem" {}
variable "instancetype" {}
variable "secgr-dynamic-ports" {}
